name: Apptainer Build Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'eolab.def'
  pull_request:
    branches:
      - main
    paths:
      - 'eolab.def'


jobs:
  build-test-container:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    name: Build Container
    steps:

      - name: Check out code for the container builds
        uses: actions/checkout@v4

      - name: Install Apptainer
        run: |
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt update
          sudo apt install -y apptainer

      - name: Build Container
        run: |
          apptainer build eolab.sif eolab.def

      - name: Login and Deploy Container
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | apptainer remote login -u "${{ secrets.GHCR_USERNAME }}" --password-stdin oras://ghcr.io
          apptainer push eolab.sif oras://ghcr.io/${GITHUB_REPOSITORY}:latest
